# Copyright (c) 2018, cPanel, LLC.
# All rights reserved.
# http://cpanel.net
#
# This is free software; you can redistribute it and/or modify it under the
# same terms as Perl itself. See L<perlartistic>.

package Colon::Config;

use 5.010;
use strict;
use warnings;

# ABSTRACT: XS helper to read a configuration file using ':' as separator


our $BACKEND;

BEGIN {

    # VERSION: generated by DZP::OurPkgVersion

    eval {
        require XSLoader;
        XSLoader::load(__PACKAGE__);
    };
    if ($@) {
        *read = \&read_pp;
        $BACKEND = 'pp';
    }
    else {
        $BACKEND = 'xs';
    }
}

sub read_pp {
    my ( $config, $field, $sep ) = @_;

    if ( defined $field ) {
        die "Colon::Config::read_pp - Second argument must be one integer.\n"
            unless $field =~ /\A\s*[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?\s*\z/;
        $field = do { no warnings; int($field) };
        die "Colon::Config::read_pp - field must be >= 0\n"
            if $field < 0;
    }
    else {
        $field = 0;
    }

    if ( defined $sep ) {
        die "Colon::Config::read_pp - Third argument must be a string.\n"
            unless !ref($sep);
        die "Colon::Config::read_pp - separator must be a single character.\n"
            unless length($sep) == 1;
        die "Colon::Config::read_pp - separator cannot be a newline, carriage return, or null character.\n"
            if $sep eq "\n" || $sep eq "\r" || $sep eq "\0";
    }
    else {
        $sep = ':';
    }

    my $sep_re = quotemeta($sep);

    my @result;
    for my $line ( split( m{\n}, $config ) ) {
        $line =~ s/\0//g;
        $line =~ s/\r+$//;
        $line =~ s/^[ \t\r\0]+//;
        next if $line eq '';
        next if $line =~ /^#/;

        my @parts = split( /$sep_re/, $line, -1 );
        next unless @parts > 1;

        my $key = $parts[0];
        next unless length $key;
        my $value;

        if ( $field == 0 ) {
            $value = join( $sep, @parts[ 1 .. $#parts ] );
            $value =~ s/^[ \t\r\0]+//;
            $value =~ s/[ \t\r]+$//;
        }
        elsif ( $field <= $#parts ) {
            $value = $parts[$field];
            $value =~ s/^[ \t\r\0]+//;
            $value =~ s/[ \t\r]+$//;
        }

        $value = undef if defined $value && !length $value;

        push @result, $key, $value;
    }

    return \@result;
}

sub read_as_hash {
    my ( $config, $field, $sep ) = @_;

    $field = 0 unless defined $field;

    my $av = defined $sep
        ? Colon::Config::read($config, $field, $sep)
        : Colon::Config::read($config, $field);
    return {} unless $av;

    return { @$av };
}


1;

=pod

=encoding utf-8

=head1 SYNOPSIS

Colon::Config sample usage

# EXAMPLE: examples/synopsis.pl

=head1 DESCRIPTION

Colon::Config

XS helper to read a configuration file using C<':'> as the default separator.
The separator can be customized via the optional third argument.

The basic operation is similar to a double split:

    [ map { ( split( m{:}, $_, 2 ) ) } split( m{\n}, $string ) ];

=head1 Basic parsing rules

=over

=item ':' is the default character separator between key and value 

=item spaces or tab characters after ':' are ignored

=item '#' indicates the beginning of a comment line

=item spaces or tab characters before a comment '#' are ignored

=item '\n' is used for detecting 'End Of line'

=back

=head1 XS / Pure Perl

Colon::Config uses an XS (C) implementation by default for performance.
If the XS library cannot be loaded (e.g. no C compiler available),
it falls back to a pure Perl implementation automatically.

You can check which backend is active:

    if ($Colon::Config::BACKEND eq 'xs') {
        # using XS (fast)
    } else {
        # using pure Perl fallback
    }

=head1 Available functions

=head2 read( $content, [ $field=0 ], [ $separator=':' ] )

Parse the string $content and return an Array Ref with the list of key/values parsed.
By default the value is the whole string after the first ':'.

You can also read the value from any custom field, where 1 is the first field after the key.

An optional third argument specifies the separator character (default C<':'>).
This must be a single character and cannot be a newline, carriage return, or null byte.

    # Parse semicolon-separated data
    my $result = Colon::Config::read("key;value1;value2", 0, ";");

    # Parse pipe-separated data with field extraction
    my $result = Colon::Config::read("name|age|city", 2, "|");  # field 2 = "city"

# EXAMPLE: t/example-fruits.t

Note: return undef when not called with a string

=head2 read_as_hash( $content, [ $field=0 ], [ $separator=':' ] )

This helper is provided as a convenient feature if you want to manipulate the Array Ref
from read as a Hash Ref.

Similarly to read you can also specify from which field the value should be read
and an optional separator character.

=head1 Benchmark

Here are some benchmarks to check the advantage of the XS helper, against a pure perl alternative.

# EXAMPLE: examples/benchmark.t

=head2 read_pp( $content, [ $field=0 ], [ $separator=':' ] )

Pure Perl implementation of C<read()>.  Produces identical output to the XS
version for all inputs and can be used as a fallback when XS compilation is
not available.

    my $result = Colon::Config::read_pp($content);

=head1 TODO

=over

=item support for custom end-of-line character

=back

=head1 LICENSE

This software is copyright (c) 2018 by cPanel, Inc.

This is free software; you can redistribute it and/or modify it under the same terms as the Perl 5 programming
language system itself.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY
APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE
SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE
OF THE SOFTWARE IS WITH YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,
REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY
WHO MAY MODIFY AND/OR REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE LIABLE TO YOU FOR DAMAGES,
INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF SUCH HOLDER OR OTHER PARTY HAS
BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

